require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/*.rb'
    - 'bin/**'
    - 'config/initializers/devise.rb'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/ExampleLength:
  Exclude:
    - 'spec/**/*_spec.rb'